// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: C5_Dual_antenna

#include "../ui.h"

void ui_ScreenS_screen_init(void)
{
    ui_ScreenS = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenS_LabelPoint = lv_label_create(ui_ScreenS);
    lv_obj_set_width(ui_ScreenS_LabelPoint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenS_LabelPoint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenS_LabelPoint, 0);
    lv_obj_set_y(ui_ScreenS_LabelPoint, 97);
    lv_obj_set_align(ui_ScreenS_LabelPoint, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenS_LabelPoint, "....");
    lv_obj_set_style_text_color(ui_ScreenS_LabelPoint, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenS_LabelPoint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenS_LabelPoint, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenS_LabelPointSelect = lv_label_create(ui_ScreenS);
    lv_obj_set_width(ui_ScreenS_LabelPointSelect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenS_LabelPointSelect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenS_LabelPointSelect, 16);
    lv_obj_set_y(ui_ScreenS_LabelPointSelect, 97);
    lv_obj_set_align(ui_ScreenS_LabelPointSelect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenS_LabelPointSelect, ".");
    lv_obj_set_style_text_font(ui_ScreenS_LabelPointSelect, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenS_LabelTitle = lv_label_create(ui_ScreenS);
    lv_obj_set_width(ui_ScreenS_LabelTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenS_LabelTitle, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_ScreenS_LabelTitle, 0);
    lv_obj_set_y(ui_ScreenS_LabelTitle, -85);
    lv_obj_set_align(ui_ScreenS_LabelTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenS_LabelTitle, " Setting ");
    lv_obj_set_style_text_font(ui_ScreenS_LabelTitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ScreenS_LabelTitle, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenS_LabelTitle, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenS_LabelTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenS_Container = lv_obj_create(ui_ScreenS);
    lv_obj_remove_style_all(ui_ScreenS_Container);
    lv_obj_set_width(ui_ScreenS_Container, 241);
    lv_obj_set_height(ui_ScreenS_Container, 187);
    lv_obj_set_x(ui_ScreenS_Container, 0);
    lv_obj_set_y(ui_ScreenS_Container, 3);
    lv_obj_set_align(ui_ScreenS_Container, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_ScreenS_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScreenS_LabelLIghtTitle = lv_label_create(ui_ScreenS_Container);
    lv_obj_set_height(ui_ScreenS_LabelLIghtTitle, 20);
    lv_obj_set_width(ui_ScreenS_LabelLIghtTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ScreenS_LabelLIghtTitle, -58);
    lv_obj_set_y(ui_ScreenS_LabelLIghtTitle, 9);
    lv_obj_set_align(ui_ScreenS_LabelLIghtTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ScreenS_LabelLIghtTitle, "Lightness:");

    ui_ScreenS_LabelLightNum = lv_label_create(ui_ScreenS_Container);
    lv_obj_set_width(ui_ScreenS_LabelLightNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenS_LabelLightNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenS_LabelLightNum, 90);
    lv_obj_set_y(ui_ScreenS_LabelLightNum, -55);
    lv_obj_set_align(ui_ScreenS_LabelLightNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenS_LabelLightNum, "100");

    ui_ScreenS_SliderLight = lv_slider_create(ui_ScreenS_Container);
    lv_slider_set_value(ui_ScreenS_SliderLight, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ScreenS_SliderLight) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_ScreenS_SliderLight,
                                                                                                        0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ScreenS_SliderLight, 159);
    lv_obj_set_height(ui_ScreenS_SliderLight, 10);
    lv_obj_set_x(ui_ScreenS_SliderLight, 27);
    lv_obj_set_y(ui_ScreenS_SliderLight, 34);
    lv_obj_clear_flag(ui_ScreenS_SliderLight, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags


    lv_obj_add_event_cb(ui_ScreenS_SliderLight, ui_event_ScreenS_SliderLight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenS, ui_event_ScreenS, LV_EVENT_ALL, NULL);

}
