// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: C5_Dual_antenna

#include "../ui.h"

void ui_ScreenW_screen_init(void)
{
    ui_ScreenW = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenW, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenW, lv_color_hex(0xF9F9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenW, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenW_Chart = lv_chart_create(ui_ScreenW);
    lv_obj_set_width(ui_ScreenW_Chart, 172);
    lv_obj_set_height(ui_ScreenW_Chart, 103);
    lv_obj_set_x(ui_ScreenW_Chart, 10);
    lv_obj_set_y(ui_ScreenW_Chart, 6);
    lv_obj_set_align(ui_ScreenW_Chart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ScreenW_Chart, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_ScreenW_Chart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ScreenW_Chart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ScreenW_Chart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 0, false, 0);
    lv_obj_set_style_bg_color(ui_ScreenW_Chart, lv_color_hex(0xFDFCF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenW_Chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScreenW_Chart, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScreenW_Chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_size(ui_ScreenW_Chart, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_ScreenW_Chart, lv_color_hex(0x808080), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenW_Chart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenW_Chart, &lv_font_montserrat_12, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_ScreenW_LabelTitle = lv_label_create(ui_ScreenW);
    lv_obj_set_width(ui_ScreenW_LabelTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenW_LabelTitle, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_ScreenW_LabelTitle, 0);
    lv_obj_set_y(ui_ScreenW_LabelTitle, -76);
    lv_obj_set_align(ui_ScreenW_LabelTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenW_LabelTitle, " CSI Waveform \n     Amplitude");
    lv_obj_set_style_text_font(ui_ScreenW_LabelTitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ScreenW_LabelTitle, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenW_LabelTitle, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenW_LabelTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenW_LabelPoint = lv_label_create(ui_ScreenW);
    lv_obj_set_width(ui_ScreenW_LabelPoint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenW_LabelPoint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenW_LabelPoint, 0);
    lv_obj_set_y(ui_ScreenW_LabelPoint, 97);
    lv_obj_set_align(ui_ScreenW_LabelPoint, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenW_LabelPoint, "....");
    lv_obj_set_style_text_color(ui_ScreenW_LabelPoint, lv_color_hex(0xBEBEBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenW_LabelPoint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenW_LabelPoint, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenW_LabelPointSelect = lv_label_create(ui_ScreenW);
    lv_obj_set_width(ui_ScreenW_LabelPointSelect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenW_LabelPointSelect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenW_LabelPointSelect, -16);
    lv_obj_set_y(ui_ScreenW_LabelPointSelect, 97);
    lv_obj_set_align(ui_ScreenW_LabelPointSelect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenW_LabelPointSelect, ".");
    lv_obj_set_style_text_font(ui_ScreenW_LabelPointSelect, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenW, ui_event_ScreenW, LV_EVENT_ALL, NULL);

}
