// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: C5_Dual_antenna

#ifndef _C5_DUAL_ANTENNA_UI_H
#define _C5_DUAL_ANTENNA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_ScreenW
void ui_ScreenW_screen_init(void);
void ui_event_ScreenW(lv_event_t * e);
extern lv_obj_t * ui_ScreenW;
extern lv_obj_t * ui_ScreenW_Chart;
extern lv_obj_t * ui_ScreenW_LabelTitle;
extern lv_obj_t * ui_ScreenW_LabelPoint;
extern lv_obj_t * ui_ScreenW_LabelPointSelect;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenWP
void ui_ScreenWP_screen_init(void);
void ui_event_ScreenWP(lv_event_t * e);
extern lv_obj_t * ui_ScreenWP;
extern lv_obj_t * ui_ScreenWP_Chart;
extern lv_obj_t * ui_ScreenWP_LabelTitle;
extern lv_obj_t * ui_ScreenWP_LabelPoint;
extern lv_obj_t * ui_ScreenWP_LabelPointSelect;
extern lv_obj_t * ui_ScreenWP_Container1;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenM
void ui_ScreenM_screen_init(void);
void ui_event_ScreenM(lv_event_t * e);
extern lv_obj_t * ui_ScreenM;
extern lv_obj_t * ui_ScreenM_LabelPoint;
extern lv_obj_t * ui_ScreenM_LabelPointSelect;
extern lv_obj_t * ui_ScreenM_Button1;
extern lv_obj_t * ui_ScreenM_Label6;
extern lv_obj_t * ui_ScreenM_Image1;
void ui_event_ScreenM_Panel1(lv_event_t * e);
extern lv_obj_t * ui_ScreenM_Panel1;
extern lv_obj_t * ui_ScreenM_Label1;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenS
void ui_ScreenS_screen_init(void);
void ui_event_ScreenS(lv_event_t * e);
extern lv_obj_t * ui_ScreenS;
extern lv_obj_t * ui_ScreenS_LabelPoint;
extern lv_obj_t * ui_ScreenS_LabelPointSelect;
extern lv_obj_t * ui_ScreenS_LabelTitle;
extern lv_obj_t * ui_ScreenS_Container;
extern lv_obj_t * ui_ScreenS_LabelLIghtTitle;
extern lv_obj_t * ui_ScreenS_LabelLightNum;
void ui_event_ScreenS_SliderLight(lv_event_t * e);
extern lv_obj_t * ui_ScreenS_SliderLight;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_272184077);    // assets/指北针.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
