// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: C5_Dual_antenna

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void PhaseCalibration_button(lv_event_t * e);
void ScreenSSliderLight_function(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
