// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: C5_Dual_antenna

#include "ui.h"

// void ScreenSSliderLight_function(lv_event_t * e)
// {
// 	// Your code here
// }

// void PhaseCalibration_button(lv_event_t * e)
// {
// 	// Your code here
// }
